const experiences = [
	{
		title: 'Techlead Power Platform',
		company: 'Malakoff Humanis',
		date: 'Mai 2024 - en cours',
		description: [
			"Conception et Développement d'application Power Apps",
			"Conception et Développement de flux Power Automate",
			'Modélisation base de données => SQL, NoSQL, SharePoint, Dataverse',
			'Suivis et gestion de projet informatique',
			'Suivis des backlogs',
			'Rédaction des livrables',
		],
		stack: 'Environnement Microsoft',
		iconBackground: 'green',
	},
	{
		title: 'Ingénieur Power Platform',
		company: 'Devoteam',
		date: 'Janvier 2024 - Mai 2024',
		stack:
			'Environnement Microsoft (PowerPlatform, PowerApps, PowerAutomate, PowerBI, SharePoint, Office365)',
		iconBackground: 'rgb(33, 150, 243)',
	},
	{
		title: 'Développeur PowerPlateform / Développeur React.js',
		company: 'Freelance',
		date: 'Juillet 2023 - en cours',
		description: [
			"Accompagnement, Conception et Développement d'application web",
			"Conception et Développement d'application Power Apps",
			"Développement d'application Power Automate",
			'Modélisation base de données => SQL, NoSQL, SharePoint, Dataverse',
			"Test d'intégration",
			'Suivis et gestion de projet informatique',
			'Suivis des backlogs',
			'Rédaction des livrables',
			'Accompagnement, support et formation d’une équipe sur les services power platform',
		],
		stack:
			'Environnement Microsoft (PowerPlatform, PowerApps, PowerAutomate, PowerBI, SharePoint, Office365), JavaScript, React.js,Node.js avec Express, MySQL',
		clients: 'Avenir Plus, BM Data Solutions',
		iconBackground: 'green',
	},
	{
		title: 'Consultant Microsoft Dynamics 365 / Développeur PowerPlateform',
		company: 'G2i365',
		date: 'Mars 2022 - Décembre 2023',
		description: [
			'Développement et conception d’application PowerApps',
			'Modélisation de base de donnée => SQL, NoSQL, SharePoint, Dataverse',
			'Développement de Flux PowerAutomate',
			'Rédaction de livrable => spécification technique et fonctionnelle',
			'Suivis et gestion de projet',
			'Accompagnement, support et formation d’une équipe sur les services power platform',
		],
		stack: 'Environnement Microsoft',
		clients: 'Malakoff Humanis, SNCF, Fonds de dotations du Louvres, Le Bélier',
		iconBackground: 'rgb(33, 150, 243)',
	},
	{
		title:
			'Consultant Microsoft Dynamics 365 / Développeur PowerPlateform - Développeur Fullstack React / Node.js',
		company: 'Alternance IBM',
		date: 'Mars 2021 - Mars 2022',
		description: [
			"Organisation et stratégie d'entreprise",
			"développement d'interface frontend et backend",
			"développement d'APIRest",
			'modélisation base de données => SQL, NoSQL, SharePoint, Dataverse',
			"Développement d'application Power Apps",
			"Développement d'application Power Automate",
			'Paramétrage Dynamics 365 Finance & Opération',
			"Test d'intégration",
			'Gestion de projet informatique',
			"Développement d'applications desktop",
			"Développement d'applications multi-couches",
			'Scrumm',
			'Suivis des backlogs',
		],
		stack:
			'JavaScript, React.js,Node.js avec Express, PHP, Angular,MySQL, Mongodb avec Mongoose, Environnement Microsoft (Power Apps, Power Automate, Power BI, SharePoint)',
		iconBackground: 'rgb(33, 150, 243)',
	},
	{
		title: 'Développeur Front-End React, React-Native',
		company: 'Cityviz',
		date: '2020 - 2021',
		description: [
			'Création de composants pour instaurer de nouveau écrans.',
			'Création et ajout de nouvelles fonctionnalités.',
			'Création et modification de endpoint sur API.',
			'Recette -Q&A',
			'Résolution de bug.',
		],
		stack:
			'React.js, React-Native, Redux, Redux-Saga, Python, PostgreSQL, Docker, YouTrack, GitLab',
		iconBackground: 'rgb(33, 150, 243)',
	},
	{
		title: 'Développeur web et web mobile',
		company: 'Etudiant à la Wild Code School',
		date: '2020 - 2021',
		description: [
			'Bootcamp sur le métier du développement web, apprentissage HTML, CSS, JavaScript, React, Node.js, MySQL, Git, Github, HTML et CSS avec les méthodes Agile et Scrum.',
			"Apprentissage par la pratique en réalisant des projets individuelle et collectif ainsi que la réalisation d'un projet client",
		],
		iconBackground: 'rgb(33, 150, 243)',
	},
	{
		title: 'Dalkia - Groupe EDF',
		company: 'Manager Opérationnel',
		date: '2019 - 2020',
		description: [
			'Management d’une équipe de huit personnes (équipe de sous-traitant multi-technique)',
			'Management de projet «Rénovation et Travaux»',
			'Interlocuteur privilégié : clients, prestataires et sous-traitants',
			'Suivis des budgets de maintenance',
			'Gamme de maintenance pilotée avec GPLI / MAINTA / SAM FM',
		],
		iconBackground: 'rgb(33, 150, 243)',
	},
	{
		title: 'Infoway - Expert en affichage dynamique',
		company: 'Responsable technique',
		date: '2018 - 2019',
		description: [
			'Management de projet national sur site et à distance',
			'Supervision des déploiements de projets',
			'Interlocuteur privilégié : Maitre d’œuvres, prestataires, développeurs',
			'Paramétrage et configuration de l’outil GMAO',
			'Gestion des demandes utilisateurs',
			'Suivis des phases recettes et tests',
			'Gestion et administration des équipements à distances',
		],
		iconBackground: 'rgb(33, 150, 243)',
	},
	{
		title: 'Ibis Bercy village',
		company: 'Responsable technique',
		date: '2015 - 2017',
		description: [
			'Membre du comité de direction',
			'Configuration de l’outil GMAO interne Accor',
			'Suivis administratif (commande / contrat / énergies)',
			'Gestion du matériel',
			'Gestion de projet',
			'Relation clientèle (gestion de conflit)',
		],
		iconBackground: 'rgb(33, 150, 243)',
	},
	{
		title: 'Mercure Paris centre Tour Eiffel',
		company: 'Assistant responsable technique',
		date: '2011 - 2015',
		description: [
			'Management équipe de neuf personnes',
			'Suivis administratif',
			'Gestion du matériel',
			'Suivis de projet',
		],
		iconBackground: 'rgb(33, 150, 243)',
		type: 'education',
	},
]

export default experiences
